/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form_Project;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.beans.PropertyChangeEvent;
import javax.swing.*;
import java.awt.*;
import java.nio.channels.Selector;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
/**
 *
 * @author daovi
 */
public class LoginForm extends javax.swing.JFrame {
    FunctionForm fc = new FunctionForm();
    String  driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    String url = "jdbc:sqlserver://localhost:1433;databaseName=Account"; 
    String user = "sa";
    String password = "123456@Ab";
    public LoginForm() {
        initComponents();
        this.setSize(550, 600);
        this.setLocationRelativeTo(null);
        this.setResizable(true);
        register__Form.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        register__Form = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lablepass = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtRepass = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        btnDK = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        txtUname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        register__Form.setBackground(new java.awt.Color(255, 255, 255));
        register__Form.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Space Mono", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(237, 37, 83));
        jLabel8.setText("REGISTER");
        register__Form.add(jLabel8);
        jLabel8.setBounds(0, 0, 130, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Rectangle 1.png"))); // NOI18N
        register__Form.add(jLabel6);
        jLabel6.setBounds(10, 90, 250, 10);

        jLabel11.setFont(new java.awt.Font("Space Mono", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Username");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        register__Form.add(jLabel11);
        jLabel11.setBounds(10, 70, 72, 20);

        jLabel12.setFont(new java.awt.Font("Space Mono", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Password");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        register__Form.add(jLabel12);
        jLabel12.setBounds(10, 130, 72, 20);

        lablepass.setFont(new java.awt.Font("Space Mono", 0, 14)); // NOI18N
        lablepass.setForeground(new java.awt.Color(153, 153, 153));
        lablepass.setText("Re-enter Password");
        lablepass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        register__Form.add(lablepass);
        lablepass.setBounds(10, 190, 153, 20);

        jLabel14.setFont(new java.awt.Font("Space Mono", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("SĐT");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        register__Form.add(jLabel14);
        jLabel14.setBounds(10, 250, 99, 20);

        txtUser.setBorder(null);
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserKeyTyped(evt);
            }
        });
        register__Form.add(txtUser);
        txtUser.setBounds(10, 70, 250, 23);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Rectangle 1.png"))); // NOI18N
        register__Form.add(jLabel15);
        jLabel15.setBounds(10, 150, 250, 10);

        txtPassword.setBorder(null);
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });
        register__Form.add(txtPassword);
        txtPassword.setBounds(10, 130, 250, 20);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Rectangle 1.png"))); // NOI18N
        register__Form.add(jLabel16);
        jLabel16.setBounds(10, 210, 250, 10);

        txtRepass.setBorder(null);
        txtRepass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRepassKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRepassKeyTyped(evt);
            }
        });
        register__Form.add(txtRepass);
        txtRepass.setBounds(10, 190, 250, 24);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Rectangle 1.png"))); // NOI18N
        register__Form.add(jLabel17);
        jLabel17.setBounds(10, 270, 250, 10);

        txtSDT.setBorder(null);
        txtSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSDTKeyTyped(evt);
            }
        });
        register__Form.add(txtSDT);
        txtSDT.setBounds(10, 250, 250, 20);

        btnDK.setFont(new java.awt.Font("Space Mono", 0, 11)); // NOI18N
        btnDK.setText("SIGN UP");
        btnDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDKActionPerformed(evt);
            }
        });
        register__Form.add(btnDK);
        btnDK.setBounds(10, 290, 250, 40);

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 21)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("X");
        jLabel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel10MouseMoved(evt);
            }
        });
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        register__Form.add(jLabel10);
        jLabel10.setBounds(242, 10, 20, 20);

        getContentPane().add(register__Form);
        register__Form.setBounds(140, 120, 270, 350);

        txtPass.setFont(new java.awt.Font("Space Mono", 3, 11)); // NOI18N
        txtPass.setBorder(null);
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        getContentPane().add(txtPass);
        txtPass.setBounds(160, 320, 250, 30);

        jLabel7.setFont(new java.awt.Font("Space Mono", 0, 11)); // NOI18N
        jLabel7.setText("Sign up now");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(290, 410, 80, 20);

        jLabel3.setFont(new java.awt.Font("Space Mono", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Not a member?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 410, 110, 20);

        jLabel5.setFont(new java.awt.Font("Space Mono", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Username");
        jLabel5.setEnabled(false);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 210, 80, 30);

        jLabel4.setFont(new java.awt.Font("Space Mono", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Password");
        jLabel4.setEnabled(false);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 290, 90, 30);

        btnDangNhap.setFont(new java.awt.Font("Space Mono", 0, 11)); // NOI18N
        btnDangNhap.setText("Login");
        btnDangNhap.setFocusPainted(false);
        btnDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDangNhapMouseClicked(evt);
            }
        });
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangNhap);
        btnDangNhap.setBounds(160, 360, 250, 40);

        txtUname.setFont(new java.awt.Font("Space Mono", 0, 12)); // NOI18N
        txtUname.setToolTipText("");
        txtUname.setBorder(null);
        txtUname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUname.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtUname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnameActionPerformed(evt);
            }
        });
        txtUname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUnameKeyPressed(evt);
            }
        });
        getContentPane().add(txtUname);
        txtUname.setBounds(160, 230, 250, 30);

        jLabel2.setFont(new java.awt.Font("Space Mono", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(237, 37, 83));
        jLabel2.setText("LOGIN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(152, 130, 110, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/LoginForm.png"))); // NOI18N
        jLabel1.setFocusTraversalPolicyProvider(true);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jLabel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jLabel1ComponentMoved(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 70, 319, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void logginEventShow() {
        
    }
    private void jLabel1ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel1ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1ComponentMoved

    private void btnDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhapMouseClicked
        // TODO add your handling code here:
        btnDangNhap.setSelected(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnDangNhapMouseClicked

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        try
        {
            Class.forName(driver);
            Connection connection =DriverManager.getConnection(url, user, password);
            String sql = "SELECT * FROM ACCOUNT where UserName=? and Pass=? ";
            PreparedStatement pst =connection.prepareStatement(sql);
           
            pst.setString(1,txtUname.getText());
            pst.setString(2,txtPass.getText());
            ResultSet rs = pst.executeQuery();
           if(txtUname.getText().equals("")||txtPass.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Bạn chưa nhập Username và Password");
            }
           else if(rs.next()){//nếu có dữ liệu
            fc.setVisible(true);
            this.dispose();
            JOptionPane.showMessageDialog(this, "Đăng nhập thành công"); 
            }
            else{
              JOptionPane.showMessageDialog(this, "Tài khoản hoặc mật khẩu không chính xác");     
            }
        }
        catch (Exception e)
        {
           JOptionPane.showMessageDialog(this, e.getMessage());
        }
       
        
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void txtUnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnameActionPerformed

    private void txtUnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnameKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtUname.transferFocus();
        }
    }//GEN-LAST:event_txtUnameKeyPressed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        register__Form.setVisible(true);
        btnDangNhap.setEnabled(false);
        
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseMoved
        // TODO add your handling code here:
        jLabel10.setForeground(Color.red);
    }//GEN-LAST:event_jLabel10MouseMoved

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        // TODO add your handling code here:
        jLabel10.setForeground(Color.gray);
    }//GEN-LAST:event_jLabel1MouseMoved

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        register__Form.setVisible(false);
        btnDangNhap.setEnabled(true);
        jLabel11.setVisible(true);
        jLabel12.setVisible(true);
        lablepass.setVisible(true);
        jLabel14.setVisible(true);
        txtUser.setText("");
        txtPassword.setText("");
        txtRepass.setText("");
        txtSDT.setText("");
        
    }//GEN-LAST:event_jLabel10MouseClicked

    private void txtUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyPressed
        // TODO add your handling code here:
                if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtUser.transferFocus();
        }
    }//GEN-LAST:event_txtUserKeyPressed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        // TODO add your handling code here:
            if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                txtPassword.transferFocus();
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void txtRepassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRepassKeyPressed
        // TODO add your handling code here:
            if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                txtRepass.transferFocus();
        }
    }//GEN-LAST:event_txtRepassKeyPressed

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
        // TODO add your handling code here:
        jLabel12.setVisible(false);
    }//GEN-LAST:event_txtPasswordKeyTyped

    private void txtSDTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSDTKeyTyped
        // TODO add your handling code here:
        jLabel14.setVisible(false);
    }//GEN-LAST:event_txtSDTKeyTyped

    private void txtRepassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRepassKeyTyped
        // TODO add your handling code here:
        lablepass.setVisible(false);
    }//GEN-LAST:event_txtRepassKeyTyped

    private void txtUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyTyped
        // TODO add your handling code here:
        jLabel11.setVisible(false);
    }//GEN-LAST:event_txtUserKeyTyped

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void btnDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDKActionPerformed
        int ch = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng ký không", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (ch != JOptionPane.YES_OPTION){
            return;
        }
        try
        {
            Class.forName(driver);
            Connection connection = DriverManager.getConnection(url, user, password);
            String sql = "INSERT INTO DBO.Account(UserName, Pass, Confirmpass, SDT) VALUES(?,?,?,?)";
            PreparedStatement pst =connection.prepareStatement(sql);
           
            pst.setString(1,txtUser.getText());
            pst.setString(2, txtPassword.getText());
            pst.setString(3,txtRepass.getText());
            pst.setString(4,txtSDT.getText());
            int dk = pst.executeUpdate();

            if(txtUser.getText().equals("")||txtPassword.getText().equals("")||txtRepass.getText().equals("")||txtSDT.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Vui lòng nhập đầy đủ thông tin đăng ký");
        
            }
            else if(dk !=0){
             JOptionPane.showMessageDialog(this, "Đăng Kí thành công"); 
            }
            else{
              JOptionPane.showMessageDialog(this, "Đăng ký thất bại");     
                    
            }
        }
        catch (Exception e)
        {
           JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnDKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDK;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lablepass;
    private javax.swing.JPanel register__Form;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtRepass;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtUname;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    private void jRadioButton1ActionPerformed(PropertyChangeEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
